$ANSIBLE_VAULT;1.1;AES256
62323636653634636536386236353665663732346331346636653239616661636665386630393065
6631366535666234656362646431653839356531663631320a333330313136616363396234343536
65643366353566646636333132313534326435633536613565366237333963383833623231366131
3934366362646634370a623933383435336364303038373231353338656138626230353330313939
30353437356235393862303164643262666266633064393533636465636237656136616364343333
39326131616636356266613162303935626131346565636462396462316638336532353138646266
306634396666366231323030373634656263
