#SPDX-License-Identifier: MIT-0
---
# handlers file for roles/nodejs

- name: Reload systemd
  command: systemctl daemon-reexec

- name: Restart nodejs app
  systemd:
    name: app
    state: restarted
